### ISSUE TITLE
Получение смысловых блоков

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/crawler#6]
Для каждой загруженной страницы получать список значений, которые удовлетворяют выражению xpath для заданного сайта.

**Comment by sergei4e** [comment]
Сделано. На вход функции get_html_elements подаем html страницу и словарь с названием параметра и регулярным выражением, а на выходе получаем словарь с названием параметра и спаршеным значением.

P.S. Только что-то намудрил с комитами..
